he = {
    "eng": "אנגלית",
    "heb": "עברית",
    "channels": "🔥 ערוצים-קבוצות",
    "create_ad":"➕ צור מודעה חדשה",
    "delete_ad":"❌ מחק מודעה",
    "add_manager":"🤝 הוסף מנהל",
    "change_language":"שנה שפה 🇮🇱/🇬🇧",
    "add_new_channel":"➕ הוסף ערוץ-קבוצה",
    "delete_channel":"❌ מחק ערוץ",
    "wellcome_message":"שלום {} *ברוך הבא* , *פרסום אוטומטי* בחסות קידום ממומן *לשירותך*🔥🔥🔥",
    "main_menu":"תפריט ראשי ⭐",
    "title_saved":"הכותרת {} נשמרה. אנא הקלד את טקסט הפוסט שלך.",
    "text_saved":"הטקסט {} נשמר. נא לשלוח אלי תמונה/סרטון/Gif או  לחץ דלג",
    "channel_id_saved":"המידע {} התקבל. *נא בחר כל כמה זמן לשלוח* את המודעה",
    "channel_name_saved":"שם הערוץ {} נשמר. נא להזין את מזהה הצ'אט",
    "channel_saved":"הערוץ\קבוצה *נשמר בהצלחה* . אתה יכול להתחיל לפרסם!",
    "button_text_saved":"השם שבחרת {} *נשמר* . נא להזין את הקישור שיוביל הכפתור",
    "button_saved":"הכפתור נשמר בהצלחה🤩!",
    "add_more_button_or_continue":"הכפתור  נוסף בהצלחה😏 רוצה להוסיף עוד כפתור?",
    "manager_added":"מנהל נוסף בהצלחה ✔️",
    "timer_saved_ad_is_running":"הטיימר הוגדר🤘🏻,  *המודעה* פעילה!",
    "what_is_the_title":"מה שם המודעה?  ( שם המודעה מה שיופיע על הכפתור כך המודעות יהיו מסודרות בבוט - זה לא מתפרסם-)",
    "what_is_the_name_of_channel":"מה שם הערוץ?",
    "please_select_channel":"אנא לחץ *על שם הערוץ שתרצה* למחוק.",
    "channel_succesfully_removed":"הערוץ *הוסר* בהצלחה🧹🧹",
    "channel_selected":"ערוץ {} נבחר. נא בחר כל כמה זמן לפרסם את המודעה.",
    "please_select_group":"אנא בחר את הקבוצה שברצונך לפרסם:",
    "what_is_the_text_of_button":"מה יהיה רשום על הכפתור🤔🤔?",
    "adding_file_skipped":"*הוספת קובץ* בחרת לדלג🙁 |  *מוסיפים כפתורים למודעה או שלא*🧐?",
    "what_is_username":"מה היוזר של המנהל?",
    "please_select_language":"אנא בחר שפה:",
    "language_succesfully_changed":"השפה שונתה בהצלחה",
    "your_channels":"⭐ הערוצים שלך:",
    "back":"⬅️ חזרה",
    "your_active_ads":"⭐ המודעות הפעילות שלך, *לחץ על שם המודעה כדי למחוק אותה*🧹🧹:",
    "file_saved_to_ad":"הקובץ נשמר במודעה.  *מוסיפים כפתורים למודעה או שלא*🧐?",
    "add_buttons":"➕ הוסף כפתור חדש",
    "continue":"דלג 😇",
    "ad_deleted":"המודעה נמחקה בהצלחה😶‍🌫️",
    "post_all_groups":"פרסם את המודעה בכל הקבוצות",
    "all_channels_selected":"החלטה נבונה🤗 עכשיו בחר , כל כמה זמן אשלח את המודעה🤫",
    "invalid_button_url":"❗❗❗ כתובת URL של לחצן לא חוקית. אנא הקלד כתובת URL נכונה. ❗❗❗",
    "skip":" ד ל ג ",
    "7_sec":"7 שניות",
    "10_sec":"10 שניות",
    "30_sec":"30 שניות",
    "45_sec":"45 שניות",
    "1_min":"דקה 1",
    "5_min":"5 דקות",
    "10_min":"10 דקות",
    "15_min":"15 דקות",
    "30_min":"30 דקות",
    "45_min":"45 דקות",
    "1_hour":"1 שעה",
    "3_hour":"3 שעות",
    "6_hour":"6 שעות",
    "9_hour":"9 שעות",
    "12_hour":"12 שעות",
    "15_hour":"15 שעות",
    "18_hour":"18 שעות",
    "24_hour":"24 שעות",
}

en = {
    "eng": "english",
    "heb": "hebrew",
    "channels":"🔥 CHANNELS",
    "create_ad":"➕ CREATE AD",
    "delete_ad":"❌ DELETE AD ",
    "add_manager":"🤝 ADD MANAGER",
    "change_language":"CHANGE LANGUAGE 🇮🇱/🇬🇧",
    "add_new_channel":"➕ ADD NEW CHANNEL",
    "delete_channel":"❌ DELETE CHANNEL",
    "wellcome_message":"Hello {} Wellcome the bot 🔥🔥🔥",
    "main_menu":"Main Menu ⭐",
    "title_saved":"Title {} saved.Please Type Your Post Text.",
    "text_saved":"Text {} saved. Please Add Image/Video/Gif or Skip",
    "channel_id_saved":"channel ID {} saved.Please Select Timer Data",
    "channel_name_saved":"Channel Name {} Saved. Please Enter Chat ID",
    "channel_saved":"Channel Succesfully Saved. You Can Use it with Your Ads",
    "button_text_saved":"Button Text {} Saved. Please Enter Button Link",
    "button_saved":"Button Succesfully Saved!",
    "add_more_button_or_continue":"Add More Button or Continue",
    "manager_added":"Manager Succesfully  Added ✔️",
    "timer_saved_ad_is_running":"Timer saved. Ad is Running",
    "what_is_the_title":"What is the title?",
    "what_is_the_name_of_channel":"What is the name of channel?",
    "please_select_channel":"Please Select a Channel You Want to Delete",
    "channel_succesfully_removed":"Channel Successfully Removed ✔",
    "channel_selected":"Channel {} Selected. Please Specify Timer Data",
    "please_select_group":"Please Select the Group You Want To Post:",
    "what_is_the_text_of_button":"What is the Text of Button",
    "adding_file_skipped":"Adding File Skipped. Add Buttons Or Continue",
    "what_is_username":"What is the Username of your manager?",
    "please_select_language":"Please Select Language:",
    "language_succesfully_changed":"Language Succesfully Changed",
    "your_channels":"⭐ Your Channels:",
    "back":"⬅️ BACK",
    "your_active_ads":"⭐ Your Active Ads:",
    "file_saved_to_ad":"File Saved to Ad. Add Buttons Or Continue",
    "add_buttons":"➕ Add Buttons",
    "continue":"Continue ✔",
    "ad_deleted":"AD SUCCESFULLY DELETED",
    "post_all_groups":"POST TO ALL GROUPS",
    "all_channels_selected":"All Channels Selected. Please Specify Timer Data",
    "invalid_button_url":"❗❗❗ Invalid Button URL.PLease Type Correct URL. ❗❗❗",
    "skip":"skip",
    "file_is_too_big":"The file you intended to upload is too big for bot, please try to upload less larger file or skip",
    "7_sec":"7 Seconds",
    "10_sec":"10 Seconds",
    "30_sec":"30 Seconds",
    "45_sec":"45 Seconds",
    "1_min":"1 Minute",
    "5_min":"5 Minutes",
    "10_min":"10 Minutes",
    "15_min":"15 Minutes",
    "30_min":"30 Minutes",
    "45_min":"45 Minutes",
    "1_hour":"1 Hour",
    "3_hour":"3 Hours",
    "6_hour":"6 Hours",
    "9_hour":"9 Hours",
    "12_hour":"12 Hours",
    "15_hour":"15 Hours",
    "18_hour":"18 Hours",
    "24_hour":"24 Hours"
}