he = {
    "eng": "אנגלית",
    "heb": "עברית",
    "channels": "🔥 ערוצים",
    "create_ad":"➕ צור מודעה",
    "delete_ad":"❌ מחק מודעה",
    "add_manager":"🤝 הוסף מנהל",
    "change_language":"שנה שפה 🇮🇱/🇬🇧",
    "add_new_channel":"➕ הוסף ערוץ חדש",
    "delete_channel":"❌ מחק ערוץ",
    "wellcome_message":"שלום {} ברוך הבא לבוט 🔥🔥🔥",
    "main_menu":"תפריט ראשי ⭐",
    "title_saved":"הכותרת {} נשמרה. אנא הקלד את טקסט הפוסט שלך.",
    "text_saved":"הטקסט {} נשמר. נא הוסף תמונה/סרטון/Gif או דלג",
    "channel_id_saved":"מזהה הערוץ {} נשמר. נא בחר נתוני טיימר",
    "channel_name_saved":"שם הערוץ {} נשמר. נא להזין את מזהה הצ'אט",
    "channel_saved":"הערוץ נשמר בהצלחה. אתה יכול להשתמש בו עם המודעות שלך",
    "button_text_saved":"טקסט לחצן {} נשמר. נא להזין קישור לחצן",
    "button_saved":"הכפתור נשמר בהצלחה!",
    "add_more_button_or_continue":"כפתור הוסף עוד או המשך",
    "manager_added":"מנהל נוסף בהצלחה ✔️",
    "timer_saved_ad_is_running":"הטיימר נשמר. המודעה פועלת",
    "what_is_the_title":"מה הכותרת?",
    "what_is_the_name_of_channel":"מה שם הערוץ?",
    "please_select_channel":"אנא בחר ערוץ שאתה רוצה למחוק",
    "channel_succesfully_removed":"הערוץ הוסר בהצלחה ✔",
    "channel_selected":"ערוץ {} נבחר. נא בחר נתוני טיימר",
    "please_select_group":"אנא בחר את הקבוצה שברצונך לפרסם:",
    "what_is_the_text_of_button":"מהו הטקסט של כפתור",
    "adding_file_skipped":"הוספת קובץ דילג. הוסף כפתורים או המשך",
    "what_is_username":"מה שם המשתמש של המנהל שלך?",
    "please_select_language":"אנא בחר שפה:",
    "language_succesfully_changed":"השפה שונתה בהצלחה",
    "your_channels":"⭐ הערוצים שלך:",
    "back":"⬅️ חזרה",
    "your_active_ads":"⭐ המודעות הפעילות שלך:",
    "file_saved_to_ad":"הקובץ נשמר במודעה. הוסף כפתורים או המשך",
    "add_buttons":"➕ הוסף לחצנים",
    "continue":"המשך ✔",
    "ad_deleted":"המודעה נמחקה בהצלחה"

}

en = {
    "eng": "english",
    "heb": "hebrew",
    "channels":"🔥 CHANNELS",
    "create_ad":"➕ CREATE AD",
    "delete_ad":"❌ DELETE AD ",
    "add_manager":"🤝 ADD MANAGER",
    "change_language":"CHANGE LANGUAGE 🇮🇱/🇬🇧",
    "add_new_channel":"➕ ADD NEW CHANNEL",
    "delete_channel":"❌ DELETE CHANNEL",
    "wellcome_message":"Hello {} Wellcome the bot 🔥🔥🔥",
    "main_menu":"Main Menu ⭐",
    "title_saved":"Title {} saved.Please Type Your Post Text.",
    "text_saved":"Text {} saved. Please Add Image/Video/Gif or Skip",
    "channel_id_saved":"channel ID {} saved.Please Select Timer Data",
    "channel_name_saved":"Channel Name {} Saved. Please Enter Chat ID",
    "channel_saved":"Channel Succesfully Saved. You Can Use it with Your Ads",
    "button_text_saved":"Button Text {} Saved. Please Enter Button Link",
    "button_saved":"Button Succesfully Saved!",
    "add_more_button_or_continue":"Add More Button or Continue",
    "manager_added":"Manager Succesfully  Added ✔️",
    "timer_saved_ad_is_running":"Timer saved. Ad is Running",
    "what_is_the_title":"What is the title?",
    "what_is_the_name_of_channel":"What is the name of channel?",
    "please_select_channel":"Please Select a Channel You Want to Delete",
    "channel_succesfully_removed":"Channel Successfully Removed ✔",
    "channel_selected":"Channel {} Selected. Please Select Timer Data",
    "please_select_group":"Please Select the Group You Want To Post:",
    "what_is_the_text_of_button":"What is the Text of Button",
    "adding_file_skipped":"Adding File Skipped. Add Buttons Or Continue",
    "what_is_username":"What is the Username of your manager?",
    "please_select_language":"Please Select Language:",
    "language_succesfully_changed":"Language Succesfully Changed",
    "your_channels":"⭐ Your Channels:",
    "back":"⬅️ BACK",
    "your_active_ads":"⭐ Your Active Ads:",
    "file_saved_to_ad":"File Saved to Ad. Add Buttons Or Continue",
    "add_buttons":"➕ Add Buttons",
    "continue":"Continue ✔",
    "ad_deleted":"AD SUCCESFULLY DELETED"

}